name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          python -m pip install black==24.8.0 flake8==7.1.1

      - name: Black check
        run: python -m black --check --diff .

      - name: Flake8
        run: python -m flake8 --max-line-length=120 --exclude .venv,__pycache__,_legacy
